# Image of workspace (using a pre-built Conda image)
image: gitpod/workspace-full:latest

# List the start up tasks
tasks:
  - name: Install Conda (if not using a pre-built image)
    # Only include this task if you're not using a pre-built Conda image
    run: |
      wget -c https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
      bash Mambaforge-$(uname)-$(uname -m).sh -b -p "${HOME}/conda"
      source "${HOME}/conda/etc/profile.d/conda.sh"
      source "${HOME}/conda/etc/profile.d/mamba.sh"

  - name: Create Conda Environment
    run: |
      conda env create -f environment.yml  # Replace with your environment file name

  - name: Activate Conda Environment
    run: |
      conda activate myenv  # Replace with your environment name

  - name: Script Task
    init: echo 'init script'
    command: echo 'start script'

# List the ports to expose
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
